version: '3'
services:
  api:
    build: .
    ports:
      - 3000
    links:
      - mongodb
    environment:
      - MONGODB_URI=${MONGODB_URI}
      
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db